### ISSUE TITLE
move to traitecoevo?

### ISSUE THREAD

**Issue by wcornwell** [traitecoevo/ksi#3]

**Comment by richfitz** [comment]
Doesn't bother me too much; the url in the paper will redirect so that's nice.  But you know I'm not interested in working much on this one any more.  Thoughts @mwpennell?

**Comment by mwpennell** [comment]
Sure — move it over. (Also maybe modeladequacy.)

**Comment by wcornwell** [comment]
hey @richfitz can you move this (and modeladequacy) over to traitecoevo, and then I'll do a bit of maintenance.

**Comment by richfitz** [comment]
done
